Repository TrustyFund/trusty-ui-vue, pull requests merged in 2018-03, with the labels that each got.

#58 Backup brainkey
  client/components/App.vue
  client/components/Backup/Backup.vue
  client/components/Backup/BackupFirst.vue
  client/components/Backup/BackupPasswordCheck.vue
  client/components/Backup/BackupPhrase.vue
  client/components/Header/Header.vue
  client/components/Header/mobile.scss
  client/style/index.scss
Labels: Work In Progress

#102 Deposit withdraw
  build/webpack.base.js
  client/app.js
  client/components/App.vue
  client/components/Backup/BackupPasswordCheck.vue
  client/components/Backup/BackupVerify.vue
  client/components/ConfirmTransactions/ConfirmTransactions.vue
  client/components/DepositWithdraw/Deposit.vue
  client/components/DepositWithdraw/Openledger/Deposit.vue
  client/components/DepositWithdraw/Openledger/Withdraw.vue
  client/components/DepositWithdraw/Transfer/WithdrawTransfer.vue
  client/components/DepositWithdraw/Trusty/Deposit.vue
  client/components/DepositWithdraw/Trusty/Payment.vue
  client/components/DepositWithdraw/Trusty/Timer.vue
  client/components/DepositWithdraw/Trusty/style.scss
  client/components/DepositWithdraw/Withdraw.vue
  client/components/DepositWithdraw/style.scss
  client/components/DepositWithdraw/temp/Deposit.js
  client/components/DepositWithdraw/temp/soso.js
  client/components/DepositWithdraw/temp/states.js
  client/components/DepositWithdraw/temp/styles.scss
  client/components/DepositWithdraw/temp/timer.js
  client/components/Login/Login.vue
  client/components/ManagePortfolio/ManagePortfolioPercent.vue
  client/components/ManagePortfolio/ManagePortfolioValue.vue
  client/components/Profile/Profile.vue
  client/components/Signup/Signup.vue
  client/components/UI/form/desk.scss
  client/components/UI/form/input.vue
  client/components/UI/form/mobile.scss
  client/components/User/User.vue
  client/router/index.js
  client/services/cryptobot.js
  client/store/index.js
  client/store/modules/cryptobot.js
  client/store/transfer.js
  package.json
  test.js
  todo
Labels: Work In Progress, feature

#157 Deposit loaders & notifications
  client/components/DepositWithdraw/Openledger/Deposit.vue
Labels: enhancement
